en:
  languageCode: en
  languageName: English
  title: My Blogs
  # Uncomment for multilingual sites, and move the default content into corresponding sub-folder.
  # contentDir: content/en

# Uncomment for multilingual sites, and customize the following config.
zh:
  languageCode: zh
  languageName: 简体中文
  contentDir: content/zh
  title: 我的博客